# Desktop core components
MEMORY_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007611'
CPU_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007671'
INTEL_MOBO_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007627'
AMD_MOBO_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007625'
GPU_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007709'
WORKSTATION_GPU_SEARCH_URL = ''
CASE_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007583'
PSU_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007657'
CASE_FANS_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100007998'
CPU_FANS_HEATSINKS_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100008000'
LIQUID_COOLING_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100008008'
SOUND_CARD_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100161258'
# Desktop storage devices
INTERNAL_HARDDRIVE_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100167523'
EXTERNAL_HARDDRIVE_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100167525'
INTERNAL_SSD_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100011693'
EXTERNAL_SSD_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100011694'
ENTERPRISE_SSD_SEARCH_URL = 'https://www.newegg.com/p/pl?N=100011695'
# Server core components
SERVER_CPU_SEARCH_URL = ''
SERVER_MEMORY_SEARCH_URL = ''
SERVER_MOBO_SEARCH_URL = ''
SERVER_CHASSIS_SEARCH_URL = ''
SERVER_PSU_SEARCH_URL = ''
SERVER_BAREBONES_SEARCH_URL = ''
CONTROLLERS_RAID_CARDS_SEARCH_URL = ''
SERVER_RACKS_CABINETS_SEARCH_URL = ''
# Mac components
MOBILE_CPU_SEARCH_URL = ''
MAC_MEMORY_SEARCH_URL = ''
MAC_HDD_SEARCH_URL = ''

DESKTOP_CORE_COMPONENTS = [
    MEMORY_SEARCH_URL,
    CPU_SEARCH_URL,
    INTEL_MOBO_SEARCH_URL,
    AMD_MOBO_SEARCH_URL,
    GPU_SEARCH_URL,
    WORKSTATION_GPU_SEARCH_URL,
    CASE_SEARCH_URL,
    PSU_SEARCH_URL,
    CASE_FANS_SEARCH_URL,
    CPU_FANS_HEATSINKS_SEARCH_URL,
    LIQUID_COOLING_SEARCH_URL,
    SOUND_CARD_SEARCH_URL,
]